sudo: required

language: node_js

node_js:
  - 7.7.2

services:
  - docker

script:
  - npm run lint
  - npm test

after_success:
  - npm run coveralls

deploy:
  provider: npm
  email: "robson.luizv@gmail.com"
  api_key:
    secure: PNVxGGp2oUF/XVy81PiBDeJsytnMu8lTiUImX6tkgqepPm6OKjKUau7vNsTH6shYGMm7bo/S6RvOAuqYZiYWbm3k1PZK/GIlHqq/zSsNV6B4fo3F1w9BpMN8xOS+kfHcpeyhm1LO0wUk4iFhzIIlmUmrMR5dBaBz6jCQj6aKFl1yRKNRzSxl4NfKA5N3mR5yPI852XR6d1nHlWafvo6Q3+7+hcedoQn8wzxmHmRWxdWUT7NG/LcoYjpGWR3zNg0/4buMuHCze+kGwQBTZnUXAN2fPBHRq+57e9Vsbxz4UK/zvaUs8wuDCppFUJ0qDtA2Jh3sM19WG97y3kETNC6mtDSdfpiszlb37ipp2/ilx8Db5KV7PGB+8tXUvjt2510o+l/ZUk/MWd3GTk5m9Og5CGTDrCZTLW6DlRmBTgew9Bssdyid2SkfkR20cU1AgsBFRLAhI/qI0CGXcLQTsnWGhKo2zqTOdZEteKgo/U/Js7N/R7TTFjPakeslxq4DmrYiMDIiwtMDRLPTHXPq0NoDq+s7BKPeIui3cS9kNxPqlHzsSh/91qrfnGphhQbHMMt0LZ/Kws53MPqSrWfgcclI0eqE9a6kNGiu+QxmOMTtud+KREo2gidq5Aa8mzHUYro8FtQfO2kCDwDD0KnqNTjVN2R7atuBmc25q6LL6INloWo=
  on:
    branch: master

after_deploy:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;

      export VERSION=$(node -p -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")
    
      docker build --build-arg version=${VERSION} -t robsonbittencourt/hubot.js:latest -t robsonbittencourt/hubot.js:${VERSION} . ;
    
      docker push docker.io/robsonbittencourt/hubot.js:latest ;

      docker push docker.io/robsonbittencourt/hubot.js:${VERSION} ;
    fi
